######################################################################
# Automatically generated by qmake (3.0) ?? 2? 20 21:04:39 2013
######################################################################

TEMPLATE = app
TARGET = colornames
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += colornamesdialog.h
SOURCES += colornamesdialog.cpp main.cpp
