######################################################################
# Automatically generated by qmake (3.0) ?? 2? 20 10:31:12 2013
######################################################################

TEMPLATE = app
TARGET = directoryviewer
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += directoryviewer.h
SOURCES += directoryviewer.cpp main.cpp

QT += widgets
