######################################################################
# Automatically generated by qmake (3.0) ?? 2? 20 22:32:03 2013
######################################################################

TEMPLATE = app
TARGET = imagepro
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += imagewindow.h transactionthread.h
FORMS += resizedialog.ui
SOURCES += imagewindow.cpp main.cpp transactionthread.cpp
