######################################################################
# Automatically generated by qmake (3.0) ?? 2? 19 22:16:48 2013
######################################################################

TEMPLATE = app
TARGET = mdieditor
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += editor.h mainwindow.h
SOURCES += editor.cpp main.cpp mainwindow.cpp
RESOURCES += mdieditor.qrc

QT += widgets
