######################################################################
# Automatically generated by qmake (3.0) ?? 2? 19 21:58:36 2013
######################################################################

TEMPLATE = app
TARGET = findfile3
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += findfiledialog.h
SOURCES += findfiledialog.cpp main.cpp

QT += widgets
