######################################################################
# Automatically generated by qmake (3.0) ?? 2? 20 21:02:36 2013
######################################################################

TEMPLATE = app
TARGET = cities
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += citymodel.h
SOURCES += citymodel.cpp main.cpp
