######################################################################
# Automatically generated by qmake (3.0) ?? 2? 20 10:38:43 2013
######################################################################

TEMPLATE = app
TARGET = calculator
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += calculator.h
SOURCES += calculator.cpp main.cpp

QT += script widgets
