######################################################################
# Automatically generated by qmake (3.0) ?? 2? 20 22:06:13 2013
######################################################################

TEMPLATE = app
TARGET = imagespace
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
SOURCES += imagespace.cpp
