######################################################################
# Automatically generated by qmake (3.0) ?? 2? 19 22:21:29 2013
######################################################################

TEMPLATE = app
TARGET = preferences
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += preferencedialog.h
SOURCES += main.cpp preferencedialog.cpp

QT += widgets
