######################################################################
# Automatically generated by qmake (3.0) ?? 2? 19 16:41:05 2013
######################################################################

TEMPLATE = app
TARGET = age
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
SOURCES += age.cpp
