######################################################################
# Automatically generated by qmake (3.0) ?? 2? 19 22:31:49 2013
######################################################################

TEMPLATE = app
TARGET = projectchooser
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += projectdialog.h projectlistwidget.h
FORMS += projectdialog.ui
SOURCES += main.cpp projectdialog.cpp projectlistwidget.cpp
RESOURCES += projectchooser.qrc

QT += widgets
