######################################################################
# Automatically generated by qmake (3.0) ?? 2? 20 22:38:49 2013
######################################################################

TEMPLATE = app
TARGET = threads
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

CONFIG       += console thread

# Input
HEADERS += thread.h threaddialog.h
SOURCES += main.cpp thread.cpp threaddialog.cpp
