######################################################################
# Automatically generated by qmake (3.0) ?? 2? 19 17:23:12 2013
######################################################################

TEMPLATE = app
TARGET = ticker
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += ticker.h
SOURCES += main.cpp ticker.cpp
