######################################################################
# Automatically generated by qmake (3.0) ?? 2? 20 15:40:05 2013
######################################################################

TEMPLATE = app
TARGET = vowelcube
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets opengl

# Input
HEADERS += vowelcube.h
SOURCES += main.cpp vowelcube.cpp
