######################################################################
# Automatically generated by qmake (3.0) ?? 2? 19 22:24:00 2013
######################################################################

TEMPLATE = app
TARGET = splitter
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += splitter.cpp

QT += widgets
