######################################################################
# Automatically generated by qmake (3.0) ?? 2? 23 19:52:19 2013
######################################################################

TEMPLATE = app
TARGET = ftpget
DEPENDPATH += .
INCLUDEPATH += .

QT			+= core widgets network ftp
CONFIG		+= console
CONFIG		-= app_bundle

# Input
HEADERS += ftpget.h
SOURCES += ftpget.cpp main.cpp
