######################################################################
# Automatically generated by qmake (3.0) ?? 2? 19 21:56:44 2013
######################################################################

TEMPLATE = app
TARGET = findfile2
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += findfiledialog.h
SOURCES += findfiledialog.cpp main.cpp

QT += widgets
