######################################################################
# Automatically generated by qmake (3.0) ?? 2? 19 17:50:06 2013
######################################################################

TEMPLATE = app
TARGET = oventimer
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += oventimer.h
SOURCES += main.cpp oventimer.cpp
