######################################################################
# Automatically generated by qmake (3.0) ?? 2? 20 21:14:35 2013
######################################################################

TEMPLATE = app
TARGET = trackeditor
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += trackdelegate.h trackeditor.h
SOURCES += main.cpp trackdelegate.cpp trackeditor.cpp
