######################################################################
# Automatically generated by qmake (3.0) ?? 2? 21 22:25:40 2013
######################################################################

TEMPLATE = app
TARGET = staffmanager
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets sql 

# Input
HEADERS += employeeform.h mainform.h
SOURCES += employeeform.cpp main.cpp mainform.cpp
