######################################################################
# Automatically generated by qmake (3.0) ?? 2? 20 10:22:54 2013
######################################################################

TEMPLATE = app
TARGET = currencies
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += currencymodel.h
SOURCES += currencymodel.cpp main.cpp

QT += gui core widgets
