######################################################################
# Automatically generated by qmake (3.0) ?? 2? 19 16:50:52 2013
######################################################################

TEMPLATE = app
TARGET = gotocell1
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
FORMS += gotocelldialog.ui
SOURCES += main.cpp
