######################################################################
# Automatically generated by qmake (3.0) ?? 2? 25 22:36:55 2013
######################################################################

TEMPLATE = app
TARGET = candy
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += candydialog.h
SOURCES += candydialog.cpp main.cpp
RESOURCES += candy.qrc
