######################################################################
# Automatically generated by qmake (3.0) ?? 2? 19 17:06:55 2013
######################################################################

TEMPLATE = app
TARGET = hexspinbox
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += hexspinbox.h
SOURCES += hexspinbox.cpp main.cpp
