######################################################################
# Automatically generated by qmake (3.0) ?? 2? 19 21:54:20 2013
######################################################################

TEMPLATE = app
TARGET = findfile1
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += findfiledialog.h
SOURCES += findfiledialog.cpp main.cpp

QT += widgets
