######################################################################
# Automatically generated by qmake (3.0) ?? 2? 19 16:47:54 2013
######################################################################

TEMPLATE = app
TARGET = find
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp
