######################################################################
# Automatically generated by qmake (3.0) ?? 2? 19 17:18:53 2013
######################################################################

TEMPLATE = app
TARGET = plotter
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += plotter.h
SOURCES += main.cpp plotter.cpp
RESOURCES += plotter.qrc
