######################################################################
# Automatically generated by qmake (3.0) ?? 2? 19 22:04:14 2013
######################################################################

TEMPLATE = app
TARGET = mailclient
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mailclient.h
SOURCES += mailclient.cpp main.cpp

QT += widgets
