######################################################################
# Automatically generated by qmake (3.0) ?? 2? 20 21:09:15 2013
######################################################################

TEMPLATE = app
TARGET = coordinatesetter
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += coordinatesetter.h
SOURCES += coordinatesetter.cpp main.cpp
