######################################################################
# Automatically generated by qmake (3.0) ?? 2? 20 14:37:30 2013
######################################################################

TEMPLATE = app
TARGET = htmleditor
DEPENDPATH += . scripts
INCLUDEPATH += .

# Input
HEADERS += htmlsyntaxhighlighter.h htmlwindow.h
FORMS += scripts/reformatdialog.ui scripts/statisticsdialog.ui
SOURCES += htmlsyntaxhighlighter.cpp htmlwindow.cpp main.cpp

QT += script widgets uitools
