######################################################################
# Automatically generated by qmake (3.0) ?? 2? 25 22:34:32 2013
######################################################################

TEMPLATE = app
TARGET = bronze
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += bronzedialog.h bronzestyle.h
SOURCES += bronzedialog.cpp bronzestyle.cpp main.cpp
RESOURCES += bronze.qrc
