######################################################################
# Automatically generated by qmake (3.0) ?? 2? 20 21:24:43 2013
######################################################################

TEMPLATE = app
TARGET = settingsviewer
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += settingsviewer.h
SOURCES += main.cpp settingsviewer.cpp
