######################################################################
# Automatically generated by qmake (3.0) ?? 2? 19 17:09:35 2013
######################################################################

TEMPLATE = app
TARGET = iconeditor
DEPENDPATH += .
INCLUDEPATH += .

QT += gui core widgets

# Input
HEADERS += iconeditor.h
SOURCES += iconeditor.cpp main.cpp
RESOURCES += iconeditor.qrc
