######################################################################
# Automatically generated by qmake (3.0) ?? 2? 20 22:14:12 2013
######################################################################

TEMPLATE = app
TARGET = domparser
DEPENDPATH += .
INCLUDEPATH += .

QT           += widgets xml
CONFIG       += console

# Input
HEADERS += domparser.h
SOURCES += domparser.cpp main.cpp
