######################################################################
# Automatically generated by qmake (3.0) ?? 2? 19 16:58:56 2013
######################################################################

TEMPLATE = app
TARGET = sort
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += sortdialog.h
FORMS += sortdialog.ui
SOURCES += main.cpp sortdialog.cpp
