######################################################################
# Automatically generated by qmake (3.0) ?? 2? 19 17:44:35 2013
######################################################################

TEMPLATE = app
TARGET = cityscape
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += annotation.h cityblock.h cityscape.h cityview.h
SOURCES += annotation.cpp cityblock.cpp cityscape.cpp cityview.cpp main.cpp
