######################################################################
# Automatically generated by qmake (3.0) ?? 2? 20 22:08:11 2013
######################################################################

TEMPLATE = app
TARGET = tidy
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += tidy.cpp

CONFIG       += console
CONFIG       -= app_bundle

QT += core
