######################################################################
# Automatically generated by qmake (3.0) ?? 2? 20 21:19:46 2013
######################################################################

TEMPLATE = app
TARGET = teamleaders
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += teamleadersdialog.h
SOURCES += main.cpp teamleadersdialog.cpp
