######################################################################
# Automatically generated by qmake (3.0) ?? 2? 20 22:37:05 2013
######################################################################

TEMPLATE = app
TARGET = semaphores
DEPENDPATH += .
INCLUDEPATH += .

CONFIG       += console thread
CONFIG       -= app_bundle

# Input
SOURCES += semaphores.cpp
