######################################################################
# Automatically generated by qmake (3.0) ?? 2? 20 22:19:36 2013
######################################################################

TEMPLATE = app
TARGET = saxhandler
DEPENDPATH += .
INCLUDEPATH += .

QT           += widgets xml
CONFIG       += console

# Input
HEADERS += saxhandler.h
SOURCES += main.cpp saxhandler.cpp
