######################################################################
# Automatically generated by qmake (3.0) ?? 2? 20 22:22:58 2013
######################################################################

TEMPLATE = app
TARGET = xmlstreamreader
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets xml

# Input
HEADERS += xmlstreamreader.h
SOURCES += main.cpp xmlstreamreader.cpp
