######################################################################
# Automatically generated by qmake (3.0) ?? 2? 20 15:29:53 2013
######################################################################

TEMPLATE = app
TARGET = tetrahedron
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets opengl

# Input
HEADERS += tetrahedron.h
SOURCES += main.cpp tetrahedron.cpp
