######################################################################
# Automatically generated by qmake (3.0) ?? 2? 20 22:26:19 2013
######################################################################

TEMPLATE = app
TARGET = xmlstreamwriter
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets xml

# Input
SOURCES += xmlstreamwriter.cpp
