######################################################################
# Automatically generated by qmake (3.0) ?? 2? 19 16:45:40 2013
######################################################################

TEMPLATE = app
TARGET = quit
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
SOURCES += quit.cpp
