######################################################################
# Automatically generated by qmake (3.0) ?? 2? 20 14:52:00 2013
######################################################################

TEMPLATE = app
TARGET = teapots
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets opengl

# Input
HEADERS += teapots.h
SOURCES += main.cpp teapots.cpp
