######################################################################
# Automatically generated by qmake (3.0) ?? 2? 20 22:41:38 2013
######################################################################

TEMPLATE = app
TARGET = waitconditions
DEPENDPATH += .
INCLUDEPATH += .

CONFIG       += console thread
CONFIG       -= app_bundle

# Input
SOURCES += waitconditions.cpp
