######################################################################
# Automatically generated by qmake (3.0) ?? 2? 21 22:01:43 2013
######################################################################

TEMPLATE = app
TARGET = scooters
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets sql

# Input
HEADERS += scooterwindow.h
SOURCES += main.cpp scooterwindow.cpp
