######################################################################
# Automatically generated by qmake (3.0) ?? 2? 19 17:25:45 2013
######################################################################

TEMPLATE = app
TARGET = diagram
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += diagramwindow.h link.h node.h propertiesdialog.h
FORMS += propertiesdialog.ui
SOURCES += diagramwindow.cpp link.cpp main.cpp node.cpp propertiesdialog.cpp
RESOURCES += resources.qrc
