######################################################################
# Automatically generated by qmake (3.0) ?? 2? 20 21:39:25 2013
######################################################################

TEMPLATE = app
TARGET = flowchartsymbolpicker
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += flowchartsymbolpicker.h
SOURCES += flowchartsymbolpicker.cpp main.cpp
RESOURCES += flowchartsymbolpicker.qrc
