######################################################################
# Automatically generated by qmake (3.0) ?? 2? 20 22:04:39 2013
######################################################################

TEMPLATE = app
TARGET = imageconverter
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += convertdialog.h
FORMS += convertdialog.ui
SOURCES += convertdialog.cpp main.cpp
